[project]
name = "storman"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "invisible-playwright",
    "playwright>=1.55.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.uv.sources]
invisible-playwright = { git = "https://github.com/feder-cr/invisible_playwright.git" }

[tool.ruff.lint]
extend-select = ["I"]
